# Generated by Django 2.2 on 2020-10-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
