# Generated by Django 2.2 on 2020-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0002_auto_20201022_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
