# Generated by Django 2.2 on 2020-10-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_sell', '0004_auto_20201022_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
